name = "demo-bible-ontology"
main = "src/index.ts"
compatibility_date = "2026-05-19"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8795

[[d1_databases]]
binding = "DB"
database_name = "bible-ontology"
database_id = "334f9f7d-f32a-48f2-b088-ff4d33295b89"

[env.production]
workers_dev = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "bible-ontology"
database_id = "334f9f7d-f32a-48f2-b088-ff4d33295b89"
